version: '3.1'
services:

  store-api:
    container_name: store-api
    build: ./
    restart: always
    command: /app/start.sh
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - store-db

  store-db:
    container_name: store-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store

